### ISSUE TITLE
OR 2023 swages seems to affect Federal AGI

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#101]
OR 2023 swages seems to affect Federal AGI

http://taxsim.nber.org/out2psl/or

First, the value in swages appears never to get reported to any of the state calculators, including this one. 
But this one is one very odd. This is a joint return with pwages=swages=81000. All runs with states except Oregon report Federal AGI as 162,000, but when I run with state=38 the emulator reports Federal AGI (v10) as 73,200. Until I get more intermediate values, I can't even speculate as to what is going on.

fiitax in the Oregon run is the same as all the other states, in  spite of the difference in reported Federal AGI.

**Comment by MaxGhenis** [comment]
Could this relate to its [federal tax liability subtraction](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/variables/gov/states/or/tax/income/subtractions/or_federal_tax_liability_subtraction.py)? @PavelMakarchuk

**Comment by PavelMakarchuk** [comment]
@feenberg @MaxGhenis worked with Al and this is due to a mapping issue - fixing in issue [#102](https://github.com/PolicyEngine/policyengine-taxsim/issues/102)
