### ISSUE TITLE
AR 2023 Joint 81Kwages Inflation Relief Credit

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#103]
AR 2023 Joint 81Kwages Inflation Relief Credit

http://taxsim.nber.org/out2psl/ar

Emulator seems to be missing the "Inflation Relief Credit" (line  7 of AR1000TC)

**Comment by PavelMakarchuk** [comment]
@feenberg I am looking at the 2023 instructions, 

It seems like in 2023 the joint filers are eligible for an inflation reduction credit amount of $100 for joint filers
![image](https://github.com/user-attachments/assets/99804cee-7415-4943-b86c-25003910583b)

**Comment by PavelMakarchuk** [comment]
I have filed a PR on the US side to make that adjustment 
[#5332](https://github.com/PolicyEngine/policyengine-us/pull/5332)

**Comment by noman404** [comment]
Closing it as fix provided in a PR in PE
