### ISSUE TITLE
RI 2023 Joint 2x81Kwages

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#104]
RI 2023 Joint 2x81Kwages

http://taxsim.nber.org/out2psl/ri

TaxAct tax is 5338, emulator shows 5088.  Could the 250 difference be a credit TaxAct is missing?

**Comment by PavelMakarchuk** [comment]
@feenberg this was due to the Child Tax Rebate which is not paid out anymore in 2023 - this will be fixed by PR [#5330](https://github.com/PolicyEngine/policyengine-us/pull/5330)
