### ISSUE TITLE
MT 2023 MFSSR 2x81Kwages

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#105]
MT 2023 MFS 2x81Kwages

http://taxsim.nber.org/out2psl/mt

TaxAct 4038+4238=8276, emulator  8494. This is married filing separately on the same return.

**Comment by PavelMakarchuk** [comment]
@feenberg this was a discrepancy in the 2023 MT parameters - I have made adjustments in PE US under PR [#5337](https://github.com/PolicyEngine/policyengine-us/pull/5337) - we should re-run this case after the PR is merged

**Comment by feenberg** [comment]
I did a "git pull" in policyengine_taxsim and it replied "Already up to 
date". The date on cli.py was November 14.  Do I need to do something else 
to get the most recent policyengine-us?

**Comment by noman404** [comment]
@feenberg you can update policyengine_us dependency separately from the environment, run this command in the root directory

`pip install policyengine_us --upgrade`
