### ISSUE TITLE
VA Joint 2x81K wages

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#106]
VA Joint 2x81K wages

http://taxsim.nber.org/out2psl/va

Taxable income matches, maybe problem with phaseout of Spouse Tax Adjustment (line 17)

**Comment by PavelMakarchuk** [comment]
@feenberg this is a discrepancy in the PE US model where we dont populate one of the intermediate variables - will fix in issue [#5327](https://github.com/PolicyEngine/policyengine-us/issues/5327)
