### ISSUE TITLE
NM 2023 Joint 2x9K wages

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#110]
NM 2023 Joint 2x9K wages

http://taxsim.nber.org/out2psl/nm

Emulator -1756, TaxAct -1599

**Comment by PavelMakarchuk** [comment]
@feenberg The difference here is the New Mexico low income comprehensive tax rebate which I believe the married household with one dependent is entitled to, I dont think TaxAct accounted for this rebate

[Table](https://klvg4oyd4j.execute-api.us-west-2.amazonaws.com/prod/PublicFiles/34821a9573ca43e7b06dfad20f5183fd/ee8f1f96-408b-47a4-a1a3-4173a71b58e7/2023pit-rc-ins.pdf)#page=5:
![image](https://github.com/user-attachments/assets/da1ad3a6-41a4-4069-9061-a0126d027f23)

**Comment by feenberg** [comment]
Yes, I went back and found where in TaxAct it was necessary to claim this.
