### ISSUE TITLE
MT 2023 Joint 2x9K wage

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#113]
MT 2023 Joint 2x9K wage

http://taxsim.nber.org/out2psl/mt

Emulator allows huge refundable credit I can't identify.

This is after policyengine_us update at 2pm Nov 18.

**Comment by PavelMakarchuk** [comment]
@feenberg the attached tax form shows joint filers with $81k each and one dependent 

Please confirm what household we are looking at here

**Comment by PavelMakarchuk** [comment]
@noman404 there seems to a difference here between the emulator and the PE US output. 
The emulator returns state income tax amount of $-5,205 but locally I am getting a number a lot closer to the TAXact 

I dont see a ctc amount in montana when running the test locally

**Comment by feenberg** [comment]
Maybe this can be resolved if I get instructions on installing and 
updating the emulator.

**Comment by noman404** [comment]
Join household support is available in this PR #88
