### ISSUE TITLE
DE 2022  Rebate

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#114]
There was a 300/600 tax rebate in Deleware paid in 2022 based on 2020 tax forms. Taxsim has shown it in 2022, but the emulator does not. Does policyengine-us have a policy about rebates? I'd like to conform, but it would be easier if I didn't have to discover them one by one.

**Comment by PavelMakarchuk** [comment]
@feenberg we have not included the 2022 rebate into the Delaware model but decided to add it in the following PR: [#5355](https://github.com/PolicyEngine/policyengine-us/pull/5355)

**Comment by PavelMakarchuk** [comment]
PR was merged
