### ISSUE TITLE
AR 2023 HOH 144K wage

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#116]
AR 2023 HOH 144K wage

http://taxsim.nber.org/out2psl/ar2

Emulator shows 371 siitax on 144000 in wage income -

**Comment by PavelMakarchuk** [comment]
@feenberg I have made some adjustments to PE US rules - added a bug fix to the 2023 AR low income tax calculation

This should be fixed once PR [#5361](https://github.com/PolicyEngine/policyengine-us/pull/5361) is merged

**Comment by noman404** [comment]
closing it as the the PR is merged
