### ISSUE TITLE
Closed but not incorporated

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#117]
I see that issues for 4 states are closed, but still show descrepancies between the emulator and TaxAct. I am guessing that I should not report new issues for these states, but I don't know how to tell if a change has made it to the main repository, or is waiting for approval. If the change has been made, these would be new issues, otherwise I should wait. Is there a way for me to tell? 

MN  http://taxsim.nber.org/out2psl/mn
MS   http://taxsim.nber.org/out2psl/ms
NM   http://taxsim.nber.org/out2psl/nm
RI      http://taxsim.nber.org/out2psl/ri

I will be in Cambridge for the next 10 days, then in California for 10 days and probably not doing much work while there. If some new input variables were added to the emulator, I could greatly increase coverage. Mortgage would allow me to test itemization. If you can only do one, that would be a good choice.  Next would be proptax,page,sage,gssi and pension. They should all be together.  But if mortgage where done very soon, I could work on itemization before leaving for California.

Note that it is difficult to continue with a state once one issue is raised, since the error output will be usually be dominated by that issue. However, if I have more intermediate data (such as taxable income, eic, etc) I can filter out the already raised issues and continue to evaluate that state.

I hope I am providing the information you need in the issues I raise. I think we are making good progress, and this is easier for me than working with Martin was.

**Comment by noman404** [comment]
please try the latest version, should be resolving the concerns
