### ISSUE TITLE
OR 2023 Child Care Credit

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#126]
OR 2023 Child Care Credit

Called the Oregon  Working Family  Household and Dependent Care Credit.

This joint return has two employed taxpayers and a single dependent with $2000 in child care expense. I don't think the emulator has calculated the WFHDC. 

http://taxsim.nber.org/out2psl/or2
https://taxsim.nber.org/historical_state_tax_forms/OR/2023/schedule-or-wfhdc_101-195_2023.pdf
https://www.oregon.gov/dor/forms/FormsPubs/publication-or-wfhdc-tb_101-458_2022.pdf

**Comment by MaxGhenis** [comment]
We calculate it as `or_working_family_household_and_dependent_care_credit`: https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/variables/gov/states/or/tax/income/credits/wfhdc/or_working_family_household_and_dependent_care_credit.py

Where would we manually map that to a list of CDCCs @noman404?

**Comment by feenberg** [comment]
I am reviving this issue with the test jig sending the emulator the correct values.

Called the Oregon Working Family Household and Dependent Care Credit.

This joint return has two employed taxpayers and a single
dependent with $2000 in child care expense. Regular tax
is 1596. TaxAct sees 708 (exemption credit) 332 (EIC) and
1280 (child care) which sends the net to -724 but the emulator
has a positive tax.

http://taxsim.nber.org/out2psl/or2
https://taxsim.nber.org/historical_state_tax_forms/OR/2023/schedule-or-wfhdc_101-195_2023.pdf
https://www.oregon.gov/dor/forms/FormsPubs/publication-or-wfhdc-tb_101-458_2022.pdf

**Comment by feenberg** [comment]
I am closing this issue and will post another that is similar but perhaps clearer.
