### ISSUE TITLE
CO 2023 Joint Child Tax Credit

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#127]
See

http://taxsim.nber.org/out2psl/co4

Colorado emulator may have missed Child Tax Credit.

**Comment by MaxGhenis** [comment]
We currently have both [`co_ctc`](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/variables/gov/states/co/tax/income/credits/ctc/co_ctc.py) and [`co_family_affordability_credit`](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/variables/gov/states/co/tax/income/credits/family_affordability/co_family_affordability_credit.py), which does this refer to?

**Comment by MaxGhenis** [comment]
[DR 0104CN](https://taxsim.nber.org/out2psl/co4/chcr%20c%20and%20s%20s%202023%20Colorado%20Form%20DR%200104CN.pdf) is co_ctc
