### ISSUE TITLE
VA 2023 Joint Child Care Deduction

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#129]
VA 2023 Joint Child Care Deduction

http://taxsim.nber.org/out2psl/va

There is a child care deduction, not credit in VA.  It looks like both Taxsm and the emulator are missing that.

**Comment by MaxGhenis** [comment]
We have [`va_child_dependent_care_expense_deduction`](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/variables/gov/states/va/tax/income/deductions/cdcc_expense/va_child_dependent_care_expense_deduction.py), is that a field in taxsim?
