### ISSUE TITLE
SC 2022 Rebate not included

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#167]
It appears that the 2022 state income tax rebate is included by the emulator in siitax for RI  but not for SC.  The SC rebate is documented at 

   https://dor.sc.gov/rebate-2022

See  also

  http://taxsim.nber.org/out2psl/sc

The emulator shows the 795 for siitax, but that does not include the rebate that brings Taxsim down to zero.

Is there a reason for the excluding the rebate in this case? What about ID MA MT and NY rebates?  Shouldn't we have uniform treatment? An argument for excluding them is that they are based on 2021 income so this gets the marginal tax rate wrong. However it does get after-tax income right, so there is no perfect answer.

**Comment by MaxGhenis** [comment]
Isn't this program based on 2021 income? It would show up in 2021 in our system if so.

**Comment by feenberg** [comment]
I will go along with that reasoning, with reservations.  It doesn't seem quite right for users that want after-tax income in 2021 which is most users of Taxsim. It isn't right for users that want marginal tax rates either, since their 2021 behavior can't be affected by a  2022 change in the law.  But going along makes validation testing much easier. 

MT issued in 2023 based on 2021 income 
   https://mtrevenue.gov/taxes/montana-tax-rebates/individual-income-tax-rebate-house-bill-192/#Rebates

NM issued in 2023 based on 2021 income
   https://www.tax.newmexico.gov/wp-content/uploads/2023/05/Rebate-deadline-address-update.pdf
  
OR apparently the rebate is a line on the form in odd years, based on the prior year income.
   https://www.oregon.gov/dor/programs/individuals/pages/kicker.aspx

RI I don't see a mention of this on the 2022 forms, and I can't tell when it was paid.

SC based on 2021 income but paid in 2022
   https://dor.sc.gov/rebate-2022
