### ISSUE TITLE
Map state code of 0 to Alaska

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-taxsim#22]
This indicates no state tax, and Alaska doesn't have one

**Comment by feenberg** [comment]
I would like to reopen this issue. It seems that state==0 is still not supported. There needs to be a way for users without state information to calculate federal tax.  Using state==2 (Alaska) was suggested as a temporary workaround. 

Test dataset:

```
year,state,age1,depx,pwages,mstat,mortgage,taxsimid,idtl
2023,0,4,1,81000,1,0,1,2
```

**Comment by noman404** [comment]
@feenberg its implemented as if there is no state passed in csv it considered as alaska, if your users frequently passed 0 as no state we have enhance it.

**Comment by feenberg** [comment]
The documentation fpr taxsim does instruct users to set state to zero for 
no state tax. Leaving state off the data has the effect of defaulting 
state to zero, so that works also.

But we need to accept an explicit state==0.

Dan

**Comment by feenberg** [comment]
Also, the web form for submitting taxsim data at

    http://taxsim.nber.org/taxsimtest

and all earlier versions of taxsim must submit every field. state==0 
allows no state to be specified on that form.

I know Alaska has no state tax, but last Tuesday I learned that you 
include the payments from the Alaska Permanent fund as negative taxes. So 
Alaska won't work as a proxy for no state tax. Perhaps Texas or Nevada 
will work.

Dan

**Comment by noman404** [comment]
Noted @feenberg i'll default it to Texas!
