### ISSUE TITLE
Return original taxsimid rather than record number

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#27]
Consider this input file:
```
taxsimid,year,mstat,state,idtl
999,2021,1,3,2
```
The output gets taxsimid wrong - it returns a 1 instead of 999.
```
taxsimid,year,state,fiitax,siitax,fica,frate,srate,ficar,t...
1,2021,3,-1400.00,-25.00,0.00,-15.30,0.00,placeholder,0.00...
```

The emulator seems to be returning the output record number rather than keeping the taxsimid.

**Comment by feenberg** [comment]
I did a git pull a few minutes ago, and  no longer get any result at all: for this input file

`ValueError: Variable ks_property_tax_credit does not exist.`

**Comment by noman404** [comment]
> Consider this input file:
> 
> ```
> taxsimid,year,mstat,state,idtl
> 999,2021,1,3,2
> ```
> 
> The output gets taxsimid wrong - it returns a 1 instead of 999.
> 
> ```
> taxsimid,year,state,fiitax,siitax,fica,frate,srate,ficar,t...
> 1,2021,3,-1400.00,-25.00,0.00,-15.30,0.00,placeholder,0.00...
> ```
> 
> The emulator seems to be returning the output record number rather than keeping the taxsimid.

Thats correct @feenberg, current implementation only returns output record number as taxsimid, could you please give some idea how the taxsimid should work? should it just return as it is or any other way?

**Comment by MaxGhenis** [comment]
It should return the original taxsimid, 999 in this case
