### ISSUE TITLE
fiitax disagreement

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#54]
I have posted a  TaxAct filled out Form 1040 at

   [http://taxsim.nber.org/out2psl](url)

together with the output from policyengine_taxsim for the corresponding Taxsim  input file

```
year,state,age1,depx,pwages,mstat,mortgage,taxsimid,idtl
2023,2,4,1,81000,1,0,1,2
```

The output file is:

```
taxsimid,year,state,fiitax,siitax,fica,tfica,v10,v11,v12,v13,v14,v17,v18,v19,v22,v23,v24,v25,v26,v27,v28,v34,v35,v36,v42,v43,v44,v45
1,2023,2,10080.5,0.0,5022.0,6196.5,0.0,0.0,0.0,13850.0,0.0,13850.0,67150.0,10080.5,0.0,0.0,0.0,0.0,81000.0,0.0,10080.5,0.0,0.0,0.0,0.0,0.0,1174.5,0.0
```

i am not sure where the 10,800 for fiitax comes from. Did I fill out the 1040 incorrectly?

**Comment by feenberg** [comment]
It turns out that when I create a link in a github comment using the link icon next to <>, clicking on it doesn't actually go to the NBER website, but to a search page at github. I don't know what is going on, but if you cut and paste the URL http://taxsim.nber.org/out2psl it should take you to the files I mentioned.

**Comment by MaxGhenis** [comment]
GitHub's link interface includes the text and link. I think you were pasting the link into the text rather than link field.

**Comment by feenberg** [comment]
I moved the information to http://taxsim.nber.org/out2psl/test1
