### ISSUE TITLE
Hawaii taxable income and tax for 2023, wages only.

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#57]
The 2023 taxpayer at http://taxsim.nber.org/out2psl/test3 is single, with 81000 wages, 1144 personal exemption and 2200 standard deduction.  I think this shold give 77656 for taxable income and 5662 for tax but the emulator gives 71752 for taxable income and 6966 for tax.

Note that the URL above is clickable, because I didn't use the link markup icon in the query editor. Mysterious.

**Comment by PavelMakarchuk** [comment]
@feenberg what is the taxsim output for the itemized deductions I believe the household is entitled to a $8103.8 state and local tax deduction

**Comment by feenberg** [comment]
TaxAct Hawaii return at https://taxsim.nber.org/out2psl/test3/test3.pdf shows the standard deduction as $3212. Where would the 8103.8 "stata and local tax deduction" appear on the Hawaii form N-11?

**Comment by PavelMakarchuk** [comment]
Line 21b 
[Worksheet](https://wwwa.fileyourtaxes.com/www17/cgi-bin/static/displayBlankPDF.pl?form=HI-ITEM-WKSHT.pdf&year=2023)
![image](https://github.com/user-attachments/assets/a81d65cf-3690-41e4-8793-4405efd269ad)

**Comment by feenberg** [comment]
I don't see state and local income tax adding up to 8103.  TaxAct shows 3959 as state liability for 2023.  

Taxsim will iterate on state income tax to overcome the endogeneity of that number, but for these comparisons I suppress that. I believe Martin did also.  It is a lot more work to iterate to a fixed point with TaxAct because it all has to be done by hand typing and clicking. In any case, that wouldn't help with this taxpayer.

**Comment by noman404** [comment]
closed with PR #88
