### ISSUE TITLE
Delaware 2023 missing personal exemption credit

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#58]
See http://taxsim.nber.org/out2psl/test4

Single 2023 taxpayer with 81000 wage income should get 110 personal credit. Emulator doesn't seem to show that.

**Comment by PavelMakarchuk** [comment]
@noman404 this is most likely an emulator issue the value of `[de_personal_credit](https://github.com/PolicyEngine/policyengine-us/blob/c037bb27dfc67fbcaffd1668713423e0097fe155/policyengine_us/variables/gov/states/de/tax/income/credits/personal/de_personal_credit.py#L4)` returns 110 for a single person with 81,000 of employment income in Delaware

**Comment by noman404** [comment]
Hi @PavelMakarchuk looking into it

**Comment by PavelMakarchuk** [comment]
@feenberg closing this issue as this was filed before the most recent emulator updates, the values align with PE US
