### ISSUE TITLE
Iowa 2023 single return 81000 wages

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#59]
At

http://taxsim.nber.org/out2psl/test5

is an Iowa return (single, 81000 wages, no deductions or dependents) where the emulator disagrees with TaxAct. The emulator shows 2923 and Tax Act (and Taxsim) show Note also3498  that the emulator doesn't seem to report any Taxable Income for Iowa.

**Comment by feenberg** [comment]
If I do a git pull in policyengine-taxsim does that update policyengine-us 
also? git claims I am up to date now. 5221 is not marked as closed. Does 
that mean it has not bee applied yet? I guess I am confused.

Thanks
dan

**Comment by PavelMakarchuk** [comment]
The PR is still under review - I will let you know once we merge

**Comment by PavelMakarchuk** [comment]
@feenberg now the PR is merged

**Comment by noman404** [comment]
closing it as resolved with a PR in PE
