### ISSUE TITLE
Remove requirements.txt

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-taxsim#6]
Currently dumped from an environment: https://github.com/PolicyEngine/policyengine-taxsim/blob/main/requirements.txt

Let's instead add the core necessary libraries, like policyengine-us (not pinned)

This should also avoid security warnings @anth-volk has received about old packages

**Comment by MaxGhenis** [comment]
Let's actually remove this now that we've moved to pyproject.toml

**Comment by noman404** [comment]
closed with PR #88
