### ISSUE TITLE
New Mexico $500 rebate

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#60]
Taxsim has been including the $500 2023 tax rebate in siitax. Tax Act and the emulator do not. This isn't a black and white issue, but I am thinking that if the Alaska permanent fund is reported for Alaska, then this rebate should be reported for New Mexico.  Both or none. What is your thinking?

Complexity is added by the fact that this rebate is paid in 2023, based on 2021 income.

We should discuss.

**Comment by PavelMakarchuk** [comment]
@feenberg we currently include the $500 rebate in our tax model but while looking at the [law](https://nmonesource.com/nmos/nmsa/en/item/4340/index.do#!fragment/zoupio-_Toc170906812/BQCwhgziBcwMYgK4DsDWszIQewE4BUBTADwBdoAvbRABwEtsBaAfX2zgEYB2ABgE4eANgAcHAEwBKADTJspQhACKiQrgCe0AOSapEQmFwJlqjdt37DIAMp5SAIQ0AlAKIAZZwDUAggDkAws5SpGAARtCk7BISQA) I read it such that the filer has the option to claim the rebate for any year between 2021 and 2023 against 2021 tax liability. I might be wrong but I want to confirm that the rebate is paid exclusively in 2023.

![image](https://github.com/user-attachments/assets/7736d4cf-5f83-41c8-9a07-486171cd105c)

**Comment by feenberg** [comment]
What year do you apply the rebate to? I can follow your practice.

**Comment by feenberg** [comment]
On the same topic - what do you do with the Colorado TABOR rebates? I apply $800 to 2023.

**Comment by PavelMakarchuk** [comment]
As per the Colorado, we apply the $800 rebate in 2023 as a refundable Sales Tax Credit

**Comment by feenberg** [comment]
I modified Taxsim to follow your lead.
