### ISSUE TITLE
North Carolina

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#64]
Same single, 2023,81000 wages, tax disagreement. See

http://taxsim.nber.org/out2psl/test7

TaxAct gets 3242 for siitax, emulator  3296. Difference is 55, I am not sure how low you want to go. With Taxsim I have never bothered with errors less than $25 unless a user pressed me.  I know Martin worried about $1 differences, are you comfortable with $25?

**Comment by PavelMakarchuk** [comment]
@feenberg this difference occurs due our computation of the Use tax in North Carolina which amounts to $55 for this single person

I don't think taxsim accounts for the use tax so we should set those manually to 0 for PE inputs when testing

**Comment by noman404** [comment]
added nc_use_tax, closed with PR #88
