### ISSUE TITLE
Idaho does not return a value for the grocery credit

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-taxsim#67]
The variable `id_grocery_credit` should have a value of $360 in the following scenario per @feenberg 

At

http://taxsim.nber.org/out2psl/test14

I have posted a TaxAct form for Idaho, joint 81K wages,one dep 2023 year. It shows a Taxable Income of 53300 while the emulator reports 67150. The emulator doesn't report a non-zero standard deduction or the Grocery Credit (line 43 of Form 40).

**Comment by feenberg** [comment]
Can you expand on your logic for this decision? Grocery credit is line 50 on the 2023 Idaho Form 40 - it seems like part of the income tax to me. I can remove it from Taxsim if there is a good reason. In the meantime, I will mark it as "not while testing against the emulator" but leave it in normal taxsimtest.

**Comment by PavelMakarchuk** [comment]
I would like to re-run the emulator case to see if the output still differs from TaxAct - the US package returned the same value as TaxAct

**Comment by PavelMakarchuk** [comment]
We do include the grocery credit in the income tax model

**Comment by noman404** [comment]
@PavelMakarchuk  we do not have any variable **{state}_grocery_credit** in the current version, which field it should be mapped to?
