### ISSUE TITLE
Minnesota 2023 81kwage joint 1 dep

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#68]
At

http://taxsim.nber.org/out2psl/test15

is the Minnesota 2023 joint return with a different standard deduction (27650 v 13825) taxable income (67175 v 48550) and tax (2664 v  4131) than the emulator for 81K wages, one dep. Also, 4800 exemption amount is zero in the emulator.

**Comment by noman404** [comment]
closed with PR #88
