### ISSUE TITLE
South Carolina 2023 81k wage joint 1 dep

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#69]
South Carolina 2023 81k wage joint 1 dep

http://taxsim.nber.org/out2psl/test16

TaxAct tax is 2154, emulator is 3630

There are 2 SC forms, the second is for the personal exemption and dependent exemption deductions.

**Comment by noman404** [comment]
Joint, household with dep implemented now, closed with PR #88
