### ISSUE TITLE
New York test does not return the exemptions amount

### ISSUE THREAD

**Issue by PavelMakarchuk** [PolicyEngine/policyengine-taxsim#78]
New York 81K wage joint one dep 2023

http://taxsim.nber.org/out2psl/test19

Note that the tax before penalty doesn't appear on the form IT-201. It is Line 62 less line 76 (3186-330=2856). That is what should match to the emulator siitax value.

The standard deduction in the emulator is 8000, but 16000 in TaxAct. Also, I think the dependent exemption (1000) is missing.

Local tests show 16,000 Standard deduction and $1,000 dependent exemption

**Comment by noman404** [comment]
Joint, household with dep implemented now, closed with PR #88
