### ISSUE TITLE
Indiana 2023 joint 81k wages one dep

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#84]
Indiana 2023 joint 81k wages one dep

http://taxsim.nber.org/out2psl/test36

Since the emulator doesn't report taxable income or exemptions, I have to guess at the problem. The emulator value of tax is consistent with taxable income of 80000. So I infer that the emulator has one exemption rather than 3, and it is for only 1000 instead of 1500.

**Comment by noman404** [comment]
Joint, household with dep implemented now, closed with PR #88
