### ISSUE TITLE
Pennsylvania 2023 joint 81k wages one dep

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#86]
Pennsylvania 2023 joint 81k wages one dep

http://taxsim.nber.org/out2psl/test38

This tax difference is small (43) but the tax reported by the emulator  implies that it is using a tax rate higher than the flat 3.07 reported by TaxAct.

**Comment by noman404** [comment]
Joint, household with dep implemented now, closed with PR #88
