### ISSUE TITLE
Need to implement dependent  

### ISSUE THREAD

**Issue by noman404** [PolicyEngine/policyengine-taxsim#87]
issues such as #54, #55, #57, #64, #67, #68, #69, #70, #71, #72, #73, #74, #77, #78, #82, #83, #84, #85, #86 all are related with dependent that currently we haven't implemented yet, we are planning to release next 

1. Single household (currently have)
2. Joint household (next release)
3. Dependent household (upcoming)

**Comment by MaxGhenis** [comment]
Duplicate of #53
