### ISSUE TITLE
Incorrect AGI

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#9]
Using Python 3.12 I find that this input file:

> year,state,depx,pwages,proptax,mstat,mortgage,taxsimid,idtl
> 2021,3,0,49000,4900,1,0,1,2

returns a Federal AGI of $59,343, rather than the correct $49,000.

**Comment by noman404** [comment]
```
simulation = {'people': {'you': {'age': {'2021': 40}, 'employment_income': {'2021': 49000}, 'real_estate_taxes': {'2021': 4900}}}, 'families': {'your family': {'members': ['you']}}, 'marital_units': {'your marital unit': {'members': ['you']}}, 'tax_units': {'your tax unit': {'members': ['you']}}, 'spm_units': {'your household': {'members': ['you']}}, 'households': {'your household': {'members': ['you'], 'state_name': {'2021': 'AZ'}}}}


simulation = Simulation(situation=simulation)
result = simulation.calculate("adjusted_gross_income")
```

**Comment by MaxGhenis** [comment]
That PE code correctly returns 49000: https://colab.research.google.com/drive/1BKwqQcrhYqIn0XIpmCgbhbFdJNYO__y9?usp=sharing

How does it differ from what the taxsim emulator does?

**Comment by feenberg** [comment]
It looks like you are using Policyengine-us directly. I was using the 
emulator. I have attached a session using taxsim_emulator.py with Python 
3.12 on our Linux cluster. Notice the 59343.20 value in the 3rd line. I 
think there is something wrong in the interface to Policyengine-us.

It would be helpful in the future if you got a labeled output format 
running. It wouldn't have to be the same as taxsim's idel==5, but 
something in the same spirit. Doesn't Python have something that will 
print the output variables with with their Python names? That would be 
fine.

Dan


On Wed, 9 Oct 2024, Al Noman wrote:

> ```
> simulation = {'people': {'you': {'age': {'2021': 40}, 'employment_income': {'2021': 49000}, 'real_estate_taxes': {'2021': 4900}}}, 'families': {'your family': {'members': ['you']}}, 'marital_units': {'your marital unit': {'members': ['you']}}, 'tax_units': {'your tax unit': {'members': ['you']}}, 'spm_units': {'your household': {'members': ['you']}}, 'households': {'your household': {'members': ['you'], 'state_name': {'2021': 'AZ'}}}}
>
>
> simulation = Simulation(situation=simulation)
> result = simulation.calculate("adjusted_gross_income")
> ```
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/PolicyEngine/policyengine-taxsim/issues/9#issuecomment-2402484315
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>
Script started on 2024-10-10 09:59:13-04:00 [TERM="xterm" TTY="/dev/pts/0" COLUMNS="104" LINES="47"]

sas1 taxsim: cat txpydata.csv
year,state,depx,pwages,proptax,mstat,mortgage,taxsimid,idtl
2021,3,0,49000,4900,1,0,1,2
sas1 taxsim: python3.12 taxsim_emulation.py txpydata.csv
running script
Chosen Output Level: full
script finished
sas1 taxsim: fold output.csv
taxsimid,year,state,fiitax,siitax,fica,frate,srate,ficar,tfica,v10,v11,v12,v13,v
14,v15,v16,v17,v18,v19,v20,v21,v22,v23,v24,v25,v26,v27,v28,v29,v30,v31,v32,v33,v
34,v35,v36,v37,v38,v39,v40,v41,v42,v43,v44,v45
1,2021,3,5137.18,0.00,placeholder,placeholder,placeholder,placeholder,placeholde
r,59343.20,0.00,0.00,14600.00,0.00,placeholder,placeholder,14600.00,44743.20,pla
ceholder,placeholder,placeholder,0.00,0.00,0.00,0.00,59343.20,0.00,5137.18,place
holder,48060.24,placeholder,0.00,placeholder,0.00,0.00,0.00,placeholder,placehol
der,placeholder,placeholder,placeholder,0.00,0.00,860.48,0.00

Script done on 2024-10-10 11:02:17-04:00 [COMMAND_EXIT_CODE="0"]

**Comment by MaxGhenis** [comment]
Understood - @noman404 could you check where the disconnect is in the emulator?

**Comment by MaxGhenis** [comment]
@noman404 please add an example indicating this is fixed and close if completed

**Comment by noman404** [comment]
For a same input it can generate identical output as taxsim35 does

input:

year,state,depx,pwages,mstat,mortgage,taxsimid,idtl
2021,3,0,49000,1,0,1,2
2021,3,0,47000,1,0,1,2

![image](https://github.com/user-attachments/assets/d7401638-1bd2-4170-86f8-c9cdb28c2aab)
