### ISSUE TITLE
Hawaii Joint16Kwage

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#91]
Hawaii Joint16Kwage

http://taxsim.nber.org/out2psl/hi

Emulator doesn't include "Refundable Food/Excise Tax Credit"

**Comment by PavelMakarchuk** [comment]
@feenberg the US model computes the $400 food/excise tax credit in this case.

I believe the outputs for this test case align, will close the issue and I believe it will be fixed once re-run
