### ISSUE TITLE
Massachussetts  2023 Joint 16Kwages

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#92]
Massachussetts  2023 Joint 16Kwages

http://taxsim.nber.org/out2psl/ma

Emulator does not include EIC or "No Tax Status" (line 27 of Form 1)

**Comment by PavelMakarchuk** [comment]
@feenberg I believe the output here was generated before the updates on the emulator PE US aligns with the expected amounts of EIC and tax amount (0)
