### ISSUE TITLE
MS 2023 bigwage single

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#95]
1 millioin dollars wage income, single MS return.

See

http://taxsim.nber.org/out2psl/ms

and note that emulator siitax is exactly twice TaxAct tax.

**Comment by PavelMakarchuk** [comment]
This was actually an issue in PolicyEngine US - will be fixed by [#5325](https://github.com/PolicyEngine/policyengine-us/pull/5325) we were missing a top bracket in 2023 which was causing the state income tax amounts to double - thank you for filing this
