### ISSUE TITLE
IA bigwage single

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#96]
IA bigwage single

http://taxsim.nber.org/out2psl/ia

Emulator shows siitax of 39534, TaxAct shows 56826.

**Comment by PavelMakarchuk** [comment]
@feenberg looking at the attached documents, I believe you have filled out Form 40 in **Idaho** - while the emulator is running state code 16 with is **Iowa** 

For **Idaho** the emulator returns the computed value of 56826 while Iowa returns 39534 which should align with TaxAct
